//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Yisaa.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class DT_GoAbroadStudy
    {
        public int Id { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<int> YearTable { get; set; }
        public string StudyName { get; set; }
        public string StudyTitle { get; set; }
        public string StudyTime { get; set; }
        public string StudyAddress { get; set; }
        public string StudyMoney { get; set; }
        public Nullable<int> AbroadTotalId { get; set; }
    }
}
