//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Yisaa.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class DT_HousingHouse
    {
        public int Id { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<int> YearTable { get; set; }
        public string HouseAddress { get; set; }
        public string Area { get; set; }
        public string HouseNature { get; set; }
        public string HouseFrom { get; set; }
        public string PropertyOwner { get; set; }
        public Nullable<int> HousingTotalId { get; set; }
    }
}
