//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Yisaa.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class DT_ProfitReport
    {
        public int Id { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<int> YearTable { get; set; }
        public string CompanyName { get; set; }
        public string BusinessScope { get; set; }
        public string RegisterMoney { get; set; }
        public string InvestmentRate { get; set; }
        public string YearProfit { get; set; }
        public string ParttimeUnit { get; set; }
        public string ParttimeUnitNature { get; set; }
        public string ParttimePost { get; set; }
        public string YearMoney { get; set; }
        public string InvestUnit { get; set; }
        public string InvestUnitNature { get; set; }
        public string InvestWay { get; set; }
        public string InvestMoney { get; set; }
        public string YearIncome { get; set; }
        public string Other { get; set; }
        public Nullable<System.DateTime> FillTime { get; set; }
        public Nullable<System.DateTime> UpdateTime { get; set; }
    }
}
