//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Yisaa.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class DT_Share
    {
        public int Id { get; set; }
        public string BeSharedPeople { get; set; }
        public Nullable<int> SharedYear { get; set; }
        public Nullable<System.DateTime> ShareBeginTime { get; set; }
        public Nullable<System.DateTime> ShareEndTime { get; set; }
        public string SharePeople { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public Nullable<int> BeSharedId { get; set; }
        public Nullable<int> ShareId { get; set; }
    }
}
