//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Yisaa.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class DT_Total
    {
        public int Id { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<int> YearTable { get; set; }
        public Nullable<System.DateTime> AddTime { get; set; }
        public Nullable<System.DateTime> UpdTime { get; set; }
        public string Status { get; set; }
        public string CheckStatus { get; set; }
        public string FileStatus { get; set; }
        public Nullable<System.DateTime> BackTime { get; set; }
        public Nullable<System.DateTime> ChkSubmitTime { get; set; }
        public Nullable<System.DateTime> HighBackTime { get; set; }
        public Nullable<System.DateTime> HighFileTime { get; set; }
        public Nullable<int> UserInfoId { get; set; }
        public Nullable<int> FamilyId { get; set; }
        public Nullable<int> RewardId { get; set; }
        public Nullable<int> RefuseGiftId { get; set; }
        public Nullable<int> ProfitId { get; set; }
        public Nullable<int> HousingId { get; set; }
        public Nullable<int> MarryChangeId { get; set; }
        public Nullable<int> WeddingandDieId { get; set; }
        public Nullable<int> GoAbroadId { get; set; }
        public Nullable<int> CrimeId { get; set; }
        public Nullable<int> IndustryChangesId { get; set; }
        public Nullable<int> ImportantId { get; set; }
        public Nullable<int> ResponsibilityId { get; set; }
        public Nullable<int> PetitionLetterId { get; set; }
        public Nullable<int> AdmonishingTalkId { get; set; }
        public Nullable<int> IncorruptTalkId { get; set; }
        public Nullable<int> ApplyByLetterId { get; set; }
        public string UserInfoAdvice1 { get; set; }
        public string FamilyAdvice1 { get; set; }
        public string RewardAdvice1 { get; set; }
        public string RefuseAdvice1 { get; set; }
        public string ProfitAdvice1 { get; set; }
        public string HousingAdvice1 { get; set; }
        public string MarryChgAdvice1 { get; set; }
        public string WeddDieAdvice1 { get; set; }
        public string AbroadAdvice1 { get; set; }
        public string CrimeAdvice1 { get; set; }
        public string IndustryAdvice1 { get; set; }
        public string ImportantAdvice1 { get; set; }
        public string ResponsAdvice1 { get; set; }
        public string LetterAdvice1 { get; set; }
        public string AdmTalkAdvice1 { get; set; }
        public string IncTalkAdvice1 { get; set; }
        public string ApplyAdvice1 { get; set; }
        public string UserInfoAdvice2 { get; set; }
        public string FamilyAdvice2 { get; set; }
        public string RewardAdvice2 { get; set; }
        public string RefuseAdvice2 { get; set; }
        public string ProfitAdvice2 { get; set; }
        public string HousingAdvice2 { get; set; }
        public string MarryChgAdvice2 { get; set; }
        public string WeddDieAdvice2 { get; set; }
        public string AbroadAdvice2 { get; set; }
        public string CrimeAdvice2 { get; set; }
        public string IndustryAdvice2 { get; set; }
        public string ImportantAdvice2 { get; set; }
        public string ResponsAdvice2 { get; set; }
        public string LetterAdvice2 { get; set; }
        public string AdmTalkAdvice2 { get; set; }
        public string IncTalkAdvice2 { get; set; }
        public string ApplyAdvice2 { get; set; }
        public Nullable<System.DateTime> UserInfoTime1 { get; set; }
        public Nullable<System.DateTime> FamilyTime1 { get; set; }
        public Nullable<System.DateTime> RewardTime1 { get; set; }
        public Nullable<System.DateTime> RefuseTime1 { get; set; }
        public Nullable<System.DateTime> ProfitTime1 { get; set; }
        public Nullable<System.DateTime> HousingTime1 { get; set; }
        public Nullable<System.DateTime> MarryChgTime1 { get; set; }
        public Nullable<System.DateTime> WeddDieTime1 { get; set; }
        public Nullable<System.DateTime> AbroadTime1 { get; set; }
        public Nullable<System.DateTime> CrimeTime1 { get; set; }
        public Nullable<System.DateTime> IndustryTime1 { get; set; }
        public Nullable<System.DateTime> ImportantTime1 { get; set; }
        public Nullable<System.DateTime> ResponsTime1 { get; set; }
        public Nullable<System.DateTime> LetterTime1 { get; set; }
        public Nullable<System.DateTime> AdmTalkTime1 { get; set; }
        public Nullable<System.DateTime> IncTalkTime1 { get; set; }
        public Nullable<System.DateTime> ApplyTime1 { get; set; }
        public Nullable<System.DateTime> UserInfoTime2 { get; set; }
        public Nullable<System.DateTime> FamilyTime2 { get; set; }
        public Nullable<System.DateTime> RewardTime2 { get; set; }
        public Nullable<System.DateTime> RefuseTime2 { get; set; }
        public Nullable<System.DateTime> ProfitTime2 { get; set; }
        public Nullable<System.DateTime> HousingTime2 { get; set; }
        public Nullable<System.DateTime> MarryChgTime2 { get; set; }
        public Nullable<System.DateTime> WeddDieTime2 { get; set; }
        public Nullable<System.DateTime> AbroadTime2 { get; set; }
        public Nullable<System.DateTime> CrimeTime2 { get; set; }
        public Nullable<System.DateTime> IndustryTime2 { get; set; }
        public Nullable<System.DateTime> ImportantTime2 { get; set; }
        public Nullable<System.DateTime> ResponsTime2 { get; set; }
        public Nullable<System.DateTime> LetterTime2 { get; set; }
        public Nullable<System.DateTime> AdmTalkTime2 { get; set; }
        public Nullable<System.DateTime> IncTalkTime2 { get; set; }
        public Nullable<System.DateTime> ApplyTime2 { get; set; }
        public string UserInfoPeople1 { get; set; }
        public string FamilyPeople1 { get; set; }
        public string RewardPeople1 { get; set; }
        public string RefusePeople1 { get; set; }
        public string ProfitPeople1 { get; set; }
        public string HousingPeople1 { get; set; }
        public string MarryChgPeople1 { get; set; }
        public string WeddDiePeople1 { get; set; }
        public string AbroadPeople1 { get; set; }
        public string CrimePeople1 { get; set; }
        public string IndustryPeople1 { get; set; }
        public string ImportantPeople1 { get; set; }
        public string ResponsPeople1 { get; set; }
        public string LetterPeople1 { get; set; }
        public string AdmTalkPeople1 { get; set; }
        public string IncTalkPeople1 { get; set; }
        public string ApplyPeople1 { get; set; }
        public string UserInfoPeople2 { get; set; }
        public string FamilyPeople2 { get; set; }
        public string RewardPeople2 { get; set; }
        public string RefusePeople2 { get; set; }
        public string ProfitPeople2 { get; set; }
        public string HousingPeople2 { get; set; }
        public string MarryChgPeople2 { get; set; }
        public string WeddDiePeople2 { get; set; }
        public string AbroadPeople2 { get; set; }
        public string CrimePeople2 { get; set; }
        public string IndustryPeople2 { get; set; }
        public string ImportantPeople2 { get; set; }
        public string ResponsPeople2 { get; set; }
        public string LetterPeople2 { get; set; }
        public string AdmTalkPeople2 { get; set; }
        public string IncTalkPeople2 { get; set; }
        public string ApplyPeople2 { get; set; }
        public Nullable<int> UserInfoStatus1 { get; set; }
        public Nullable<int> FamilyStatus1 { get; set; }
        public Nullable<int> RewardStatus1 { get; set; }
        public Nullable<int> RefuseStatus1 { get; set; }
        public Nullable<int> ProfitStatus1 { get; set; }
        public Nullable<int> HousingStatus1 { get; set; }
        public Nullable<int> MarryChgStatus1 { get; set; }
        public Nullable<int> WeddDieStatus1 { get; set; }
        public Nullable<int> AbroadStatus1 { get; set; }
        public Nullable<int> CrimeStatus1 { get; set; }
        public Nullable<int> IndustryStatus1 { get; set; }
        public Nullable<int> ImportantStatus1 { get; set; }
        public Nullable<int> ResponsStatus1 { get; set; }
        public Nullable<int> LetterStatus1 { get; set; }
        public Nullable<int> AdmTalkStatus1 { get; set; }
        public Nullable<int> IncTalkStatus1 { get; set; }
        public Nullable<int> ApplyStatus1 { get; set; }
        public Nullable<int> UserInfoStatus2 { get; set; }
        public Nullable<int> FamilyStatus2 { get; set; }
        public Nullable<int> RewardStatus2 { get; set; }
        public Nullable<int> RefuseStatus2 { get; set; }
        public Nullable<int> ProfitStatus2 { get; set; }
        public Nullable<int> HousingStatus2 { get; set; }
        public Nullable<int> MarryChgStatus2 { get; set; }
        public Nullable<int> WeddDieStatus2 { get; set; }
        public Nullable<int> AbroadStatus2 { get; set; }
        public Nullable<int> CrimeStatus2 { get; set; }
        public Nullable<int> IndustryStatus2 { get; set; }
        public Nullable<int> ImportantStatus2 { get; set; }
        public Nullable<int> ResponsStatus2 { get; set; }
        public Nullable<int> LetterStatus2 { get; set; }
        public Nullable<int> AdmTalkStatus2 { get; set; }
        public Nullable<int> IncTalkStatus2 { get; set; }
        public Nullable<int> ApplyStatus2 { get; set; }
        public string Remark { get; set; }
    }
}
