//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Yisaa.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class DT_UserInfo
    {
        public int Id { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<int> YearTable { get; set; }
        public string Photo { get; set; }
        public string RealName { get; set; }
        public string Sex { get; set; }
        public string NativePlace { get; set; }
        public Nullable<System.DateTime> Birthday { get; set; }
        public string IdCardNum { get; set; }
        public string Outlook { get; set; }
        public Nullable<System.DateTime> PartyTime { get; set; }
        public string Nation { get; set; }
        public string Property { get; set; }
        public Nullable<System.DateTime> JobTime { get; set; }
        public string Education { get; set; }
        public string WorkUnit { get; set; }
        public string Post { get; set; }
        public string PostStatus { get; set; }
        public Nullable<System.DateTime> PostTime { get; set; }
        public string DoWork { get; set; }
        public string UserAddress { get; set; }
        public string Introduction { get; set; }
        public Nullable<System.DateTime> FillTime { get; set; }
        public Nullable<System.DateTime> UpdateTime { get; set; }
        public string Remark { get; set; }
    }
}
