//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Yisaa.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class DT_UserLoginRecord
    {
        /// <summary>
        /// 自增ID
        /// </summary>
        public int Id { get; set; }
        /// <summary>
        /// 电话号码
        /// </summary>
        public string Telphone { get; set; }
        /// <summary>
        /// 密码
        /// </summary>
        public string Password { get; set; }
        /// <summary>
        /// 登录时间
        /// </summary>
        public Nullable<System.DateTime> LoginTime { get; set; }
        /// <summary>
        /// 登录IP
        /// </summary>
        public string LoginIp { get; set; }
        /// <summary>
        /// 登录次数
        /// </summary>
        public Nullable<int> LoginNum { get; set; }
        /// <summary>
        /// 备注
        /// </summary>
        public string Remark { get; set; }
        /// <summary>
        /// 角色ID
        /// </summary>
        public Nullable<int> RoleId { get; set; }
        /// <summary>
        /// 是否内部成员
        /// </summary>
        public Nullable<bool> IsInner { get; set; }
        /// <summary>
        /// 是否科级干部
        /// </summary>
        public Nullable<bool> IsCadre { get; set; }
        /// <summary>
        /// 单位ID
        /// </summary>
        public Nullable<int> WorkUnitId { get; set; }
       
        public Nullable<int> DeptId { get; set; }
        public Nullable<System.DateTime> Effectivedate { get; set; }
        /// <summary>
        /// 提交状态
        /// </summary>
        public Nullable<bool> Status { get; set; }
        /// <summary>
        /// 真实姓名
        /// </summary>
        public string RealName { get; set; }
        public string WorkUnit { get; set; }
        public string Department { get; set; }
        public string Upost { get; set; }
        public string FillStatus { get; set; }
        /// <summary>
        /// 共享状态
        /// </summary>
        public string ShareStatus { get; set; }
        /// <summary>
        /// 添加时间
        /// </summary>
        public Nullable<System.DateTime> AddTime { get; set; }
        /// <summary>
        /// 修改时间
        /// </summary>
        public Nullable<System.DateTime> UpdateTime { get; set; }
    }
}
