//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Yisaa.DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class db_gblzEntities : DbContext
    {
        public db_gblzEntities()
            : base("name=db_gblzEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<DT_BeShared> DT_BeShared { get; set; }
        public DbSet<DT_BuildTime> DT_BuildTime { get; set; }
        public DbSet<DT_Role> DT_Role { get; set; }
        public DbSet<DT_Share> DT_Share { get; set; }
        public DbSet<DT_SharePeople> DT_SharePeople { get; set; }
        public DbSet<DT_Total> DT_Total { get; set; }
        public DbSet<DT_UnitDeptChange> DT_UnitDeptChange { get; set; }
        public DbSet<DT_UserLoginRecord> DT_UserLoginRecord { get; set; }
        public DbSet<DT_WorkUnit> DT_WorkUnit { get; set; }
        public DbSet<DT_RefuseGiftTotal> DT_RefuseGiftTotal { get; set; }
        public DbSet<DT_UserInfo> DT_UserInfo { get; set; }
        public DbSet<DT_AdmonishingTalk> DT_AdmonishingTalk { get; set; }
        public DbSet<DT_ApplyByLetter> DT_ApplyByLetter { get; set; }
        public DbSet<DT_CrimeReport> DT_CrimeReport { get; set; }
        public DbSet<DT_FamilyTotal> DT_FamilyTotal { get; set; }
        public DbSet<DT_Important> DT_Important { get; set; }
        public DbSet<DT_IncorruptTalk> DT_IncorruptTalk { get; set; }
        public DbSet<DT_IndustryChanges> DT_IndustryChanges { get; set; }
        public DbSet<DT_MarryChange> DT_MarryChange { get; set; }
        public DbSet<DT_PetitionLetter> DT_PetitionLetter { get; set; }
        public DbSet<DT_ProfitReport> DT_ProfitReport { get; set; }
        public DbSet<DT_Responsibility> DT_Responsibility { get; set; }
        public DbSet<DT_WeddingandDie> DT_WeddingandDie { get; set; }
        public DbSet<DT_GoAbroadCompany> DT_GoAbroadCompany { get; set; }
        public DbSet<DT_HousingBuild> DT_HousingBuild { get; set; }
        public DbSet<DT_HousingBuy> DT_HousingBuy { get; set; }
        public DbSet<DT_HousingHouse> DT_HousingHouse { get; set; }
        public DbSet<DT_HousingRentout> DT_HousingRentout { get; set; }
        public DbSet<DT_HousingSell> DT_HousingSell { get; set; }
        public DbSet<DT_HousingTotal> DT_HousingTotal { get; set; }
        public DbSet<DT_RewardPunishTotal> DT_RewardPunishTotal { get; set; }
        public DbSet<DT_Family> DT_Family { get; set; }
        public DbSet<DT_GoAbroadSettler> DT_GoAbroadSettler { get; set; }
        public DbSet<DT_GoAbroadStudy> DT_GoAbroadStudy { get; set; }
        public DbSet<DT_GoAbroadTotal> DT_GoAbroadTotal { get; set; }
        public DbSet<DT_Punish> DT_Punish { get; set; }
        public DbSet<DT_RefuseGift> DT_RefuseGift { get; set; }
        public DbSet<DT_Reward> DT_Reward { get; set; }
    }
}
